baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Gurukulams School"
defaultContentLanguage = "en"

[Languages]
[Languages.en]
weight = 0
languagename = "English"
contentDir = 'content.en'


[Languages.ta]
weight = 1
languagename = "தமிழ்"
contentDir = 'content.ta'
