name = "Ananke Gohugo Theme"
license = "MIT"
languageCode = "en-us"
languageLang = "en"

[Languages]
[Languages.en]
weight = 0
languagename = "English"
contentDir = 'content.en'

[Languages.ta]
weight = 1
languagename = "தமிழ்"
contentDir = 'content.ta'